# golangci-lint configuration for k1s project
# High-quality linting configuration with 50+ linters for production readiness
version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  skip-dirs:
    - vendor
    - .backup
    - bin
  skip-files:
    - ".*_generated\\.go$"
    - "zz_generated.*\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - importShadow
      - paramTypeCombine
      - rangeValCopy
  govet:
    enable-all: true
    disable:
      - fieldalignment # Can be overly strict for readability
  revive:
    # Minimal configuration - only enable essential rules, skip problematic ones
    rules:
      - name: unused-parameter
      - name: error-return
      - name: error-naming
      - name: var-naming
  staticcheck:
    checks: ["all"]
  gosec:
    excludes:
      - G204 # Subprocess launched with variable - needed for CLI tools
      - G304 # File path provided as taint input - needed for storage backends
  goimports:
    local-prefixes: github.com/dtomasi/k1s
  funlen:
    lines: 100
    statements: 60
  cyclop:
    max-complexity: 15
  nestif:
    min-complexity: 4
  testpackage:
    skip-regexp: (export|internal)_test\.go

linters:
  disable-all: true
  enable:
    # Core linters (always available)
    - errcheck
    - govet
    - ineffassign
    - unused
    
    # Style and formatting  
    - gocyclo
    - goconst
    - gocritic
    # revive disabled due to dot-imports issue with Ginkgo tests
    
    # Performance and security
    - gosec
    - unconvert
    - misspell
    - unparam
    
    # Code quality
    - dupl
    - nolintlint

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
        - gocritic
        - gocognit
        - funlen
        - gomnd
    
    # Allow dot imports in test files (standard for Ginkgo/Gomega tests)
    - path: "_test\\.go$"
      linters:
        - revive
      text: "should not use dot imports"
    
    # Exclude generated files
    - path: zz_generated\..*\.go
      linters:
        - revive
        - stylecheck
        - godot
        - gocritic
        - staticcheck
        - unused
    
    # Exclude some staticcheck checks for test files
    - path: _test\.go
      text: "SA1019:"
      
    # Allow embedding of interfaces in tests
    - path: _test\.go
      text: "embed"
      linters:
        - govet
        
    # Allow embedded field access in test DeepCopy implementations
    - path: _test\.go
      text: "QF1008:"
      linters:
        - staticcheck
        
    # Allow underscore assignments for ignored return values
    - linters:
        - errcheck
      text: "Error return value.*is not checked"
      source: "^\\s*_\\s*="

  # Maximum count of issues with the same text, 0 means unlimited
  max-same-issues: 0
  
  # Maximum issues count per one linter, 0 means unlimited  
  max-issues-per-linter: 0