name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # Run comprehensive quality checks on all supported Go versions
  quality-checks:
    name: Quality Checks
    uses: ./.github/workflows/quality-checks.yml
    with:
      go-version: "1.24.0"

  # Test on multiple Go versions and platforms for release compatibility
  test-matrix:
    name: Multi-Version Test Matrix
    needs: quality-checks
    uses: ./.github/workflows/test-matrix.yml
    with:
      go-versions: '["1.23.0", "1.24.0"]'
      os-matrix: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      coverage-upload: true

  # Build and security scan for release artifacts
  build-security:
    name: Build & Security
    needs: test-matrix
    uses: ./.github/workflows/build-security.yml
    with:
      go-version: "1.24.0"
      run-benchmarks: true
      run-security-scan: true

  # TODO: Release preparation and artifact creation will be implemented later